// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvejjg-PoV7xCTdm5-_K2EKSOfOjsI6zM',
    appId: '1:877638133005:web:9c065a391e213b43d3bc44',
    messagingSenderId: '877638133005',
    projectId: 'deeplinking-3d2f9',
    authDomain: 'deeplinking-3d2f9.firebaseapp.com',
    storageBucket: 'deeplinking-3d2f9.appspot.com',
    measurementId: 'G-RXQD76GHWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwa4pprMC5mO7XIGkloKowDN6LSF0Olj8',
    appId: '1:877638133005:android:e2a09081374eca86d3bc44',
    messagingSenderId: '877638133005',
    projectId: 'deeplinking-3d2f9',
    storageBucket: 'deeplinking-3d2f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcUsF1P1EVx4CFc5k80_u5u1FzIUBMh_U',
    appId: '1:877638133005:ios:0ebaca276a3f5a92d3bc44',
    messagingSenderId: '877638133005',
    projectId: 'deeplinking-3d2f9',
    storageBucket: 'deeplinking-3d2f9.appspot.com',
    iosClientId: '877638133005-4knrerke7deiub6lj0fi6o77qn9vlqik.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcUsF1P1EVx4CFc5k80_u5u1FzIUBMh_U',
    appId: '1:877638133005:ios:0ebaca276a3f5a92d3bc44',
    messagingSenderId: '877638133005',
    projectId: 'deeplinking-3d2f9',
    storageBucket: 'deeplinking-3d2f9.appspot.com',
    iosClientId: '877638133005-4knrerke7deiub6lj0fi6o77qn9vlqik.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipProject',
  );
}
